### ISSUE TITLE
Can't use this plugin

### ISSUE THREAD

**Issue by 2856571872** [Wallethub/cordova-plugin-sslsupport#1]
cordova plugin add https://github.com/Wallethub/cordova-plugin-sslsupport.git
error message:
'''
Fetching plugin "https://github.com/Wallethub/cordova-plugin-sslsupport.git" via git clone
Repository "https://github.com/Wallethub/cordova-plugin-sslsupport.git" checked out to git ref "master".
Error: Failed to fetch plugin https://github.com/Wallethub/cordova-plugin-sslsupport.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: No whitespace between attributes
Line: 13
Column: 46
Char: v
'''

**Comment by Wallethub** [comment]
It has been resolved
