### ISSUE TITLE
SSL Certificate not installing or need help

### ISSUE THREAD

**Issue by sanket-webmavens** [Wallethub/cordova-plugin-sslsupport#2]
Thanks for creating this plugin, I am not sure you are still maintaining this or not, but I need your help to understand the workflow.

I am adding a certificate.cer file as per your instructions in the root folder and also in config.xml. 

My question is if I am defining this all can I see the certificate details when we inspect the APK in the chrome inspector as we can do in the browser. If yes I am not able to see that.

https://paste.webmavens.com/GKbl1StVPX.paste

By using this plugin I want to make a secure socket connection to wss:// URL. But I can't achieve that and always getting error "net::ERR_CONNECTION_REFUSED". Please let me if I can use this plugin for this specific purpose or not. If possible please guide me for that. I want to use the wss:// socket URL to connect a webrtc stream.

Thanks again!!

**Comment by Wallethub** [comment]
That type of message is thrown by the webivew, not by a native call. The plugin is focused on doing HTTP requests via native calls. The webview itself cannot use it. So no, you cannot use this plugin, as it for websockets.
