### ISSUE TITLE
pining not working and even wihtout certificate it gives pining enabled success messages 

### ISSUE THREAD

**Issue by dilanWijerathne** [Wallethub/cordova-plugin-sslsupport#4]
>  window.sslHTTP.enableSSLPinning(true, function () {
        // Congratulations, you have set up SSL pinning.
        console.log('enable SSLPinning success');
      }, function () {
        console.log('enable SSLPinning error');
        thats.sslpinningModeView.open();
        // Boooooo, SSL pinning failed.
      });

Even without have a certificate file this gives :         console.log('enable SSLPinning success');

and when add a certificate it again says :         console.log('enable SSLPinning success');
 but pining does not work really for post calls it can be intercepted via burp

**Comment by Wallethub** [comment]
@dilanWijerathne please give details about your tests, start with what platform you tested on (Android or iOS?)
