### ISSUE TITLE
SSL check does not work - response is always OK

### ISSUE THREAD

**Issue by jammin197** [Wallethub/cordova-plugin-sslsupport#5]
Hello,

today I tried to integrate your plugin into my **Android** application. I followed every single step in your guide, but SSL does not work. Response is always OK, even when I replace certificate by another one from totally different domain. Did you try also this case? I do not know what is wrong.

config.xml
```
<!-- domain pinning -->
<resource-file src="certificates/Sectigo_RSA_Domain_Validation_Secure_Server_CA.crt" target="assets/certificates/azet.sk.crt" />
<!-- subdomain pinning -->
<resource-file src="certificates/_.azet.sk.crt" target="assets/certificates/www.azet.sk.crt" />
```
in angular service
```
const params = {
	url : 'https://www.ppe2.net/.../.../'
};

sslHTTP.get(params, (response) => {
	console.log('This success is always returned');
	console.log(response);
	console.log(response.data);
}, (error) => {
	console.log('I expected that this part would be executed, because I changed the original certificate');
	console.log(error);
});
```

**Comment by Wallethub** [comment]
The domain you are pinning against represents for which requests the pinning will happen. Example:
```
<resource-file src="../certificates/cloudflare.cer" target="app/src/main/assets/certificates/wallethub.com.cer" />
<resource-file src="../certificates/wallethub.pem" target="app/src/main/assets/certificates/cdn.wallethub.com.pem" />
```
This means any call to wallethub.com will have pinning. You are pinning against www.azet.sk but your example has a GET call to https://www.ppe2.net

**Comment by Wallethub** [comment]
The domain you are pinning against represents for which requests the pinning will happen. Example:
```
<resource-file src="../certificates/cloudflare.cer" target="app/src/main/assets/certificates/wallethub.com.cer" />
<resource-file src="../certificates/wallethub.pem" target="app/src/main/assets/certificates/cdn.wallethub.com.pem" />
```
This means any call to wallethub.com will have pinning. You are pinning against www.azet.sk but your example has a GET call to https://www.ppe2.net
